analyzer:
  exclude: [lib/**.config.dart, lib/**.g.dart]
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    avoid_dynamic_calls: false
    no_default_cases: false
    implementation_imports: false
