name: routing_app
description: Routing app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.5
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_google_places: ^0.3.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.1

  google_maps_webservice: ^0.0.20-nullsafety.5
  intl: ^0.18.0
  url_launcher: ^6.1.11

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
